In [1]:
from TransformerModules import Transformer, PTC
from TransformerModules1 import Transformer1
from Operators import D_WC
from BasicFunctions import *

>Model testing

In [2]:
new_gauge = torch.rand(*LATTICE, GAUGE_DOF, GAUGE_DOF, dtype=torch.complex128)
new_gauge, r_matrix = torch.linalg.qr(new_gauge)

In [3]:
test_field = torch.rand(NUM_OF_LATTICES, *LATTICE, GAUGE_DOF, NON_GAUGE_DOF, dtype=torch.complex128)

In [4]:
M = Transformer(GAUGE_FIELD_SMALL, NON_GAUGE_DOF, 128, False)
# M = Transformer1(GAUGE_FIELD_SMALL, NON_GAUGE_DOF, 64)
# test_field = torch.rand(NUM_OF_LATTICES, *LATTICE, GAUGE_DOF, NON_GAUGE_DOF, dtype=torch.complex128)
# M = SuperPtc(GAUGE_FIELD_SMALL, NON_GAUGE_DOF)

In [5]:
y_field = gauge_tra(M(test_field), new_gauge)

In [6]:
M.gauge_tra(new_gauge)
x_field = M(gauge_tra(test_field, new_gauge))

In [7]:
y_field[0][0][0][0][0]

tensor([[-1.3461-1.3792j,  3.1259-0.1730j, -0.5660-1.2627j, -0.7557+1.5772j],
        [-1.4024-2.9663j,  1.6337-0.5697j, -0.3096+0.1507j, -0.0695+0.6956j],
        [-0.1224+0.0109j, -0.7392-1.2503j, -1.1862+0.7712j,  0.0548+1.1064j]],
       dtype=torch.complex128, grad_fn=<SelectBackward0>)

In [8]:
x_field[0][0][0][0][0]

tensor([[-1.3461-1.3792j,  3.1259-0.1730j, -0.5660-1.2627j, -0.7557+1.5772j],
        [-1.4024-2.9663j,  1.6337-0.5697j, -0.3096+0.1507j, -0.0695+0.6956j],
        [-0.1224+0.0109j, -0.7392-1.2503j, -1.1862+0.7712j,  0.0548+1.1064j]],
       dtype=torch.complex128, grad_fn=<SelectBackward0>)

In [9]:
torch.max(torch.norm((x_field - y_field).view(-1)))

tensor(9.7320e-13, dtype=torch.float64, grad_fn=<MaxBackward1>)

In [17]:
torch.mean(torch.abs(y_field))

tensor(0.1910, dtype=torch.float64, grad_fn=<MeanBackward0>)

>Operators testing

In [18]:
d_wc = D_WC(M, GAUGE_FIELD_SMALL)

In [19]:
test_field = torch.rand(NUM_OF_LATTICES, *LATTICE, GAUGE_DOF, NON_GAUGE_DOF, dtype=torch.complex128)

In [20]:
x = gauge_tra(d_wc(test_field), new_gauge)

In [21]:
d_wc.gauge_tra(new_gauge)
y = d_wc(gauge_tra(test_field, new_gauge))

In [22]:
x[0,0,0,0,0]

tensor([[ 1.6288-0.6935j, -1.5211-0.1333j, -3.2507-0.7626j, -0.2517-0.7952j],
        [-1.0042-4.4230j, -0.7003-3.8821j,  0.4384-3.3364j, -0.8399-4.5116j],
        [ 0.6227+0.3115j, -0.2356-3.8477j, -0.4231+1.8748j, -1.8215+0.3495j]],
       dtype=torch.complex128)

In [23]:
y[0,0,0,0,0]

tensor([[ 1.6288-0.6935j, -1.5211-0.1333j, -3.2507-0.7626j, -0.2517-0.7952j],
        [-1.0042-4.4230j, -0.7003-3.8821j,  0.4384-3.3364j, -0.8399-4.5116j],
        [ 0.6227+0.3115j, -0.2356-3.8477j, -0.4231+1.8748j, -1.8215+0.3495j]],
       dtype=torch.complex128)

In [24]:
torch.mean(torch.abs(x - y))

tensor(1.1937e-15, dtype=torch.float64)